# Google Cloud Build configuration for automated deployment

steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Build the project
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy the function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'humidity-monitor'
      - '--runtime=nodejs20'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--source=.'
      - '--entry-point=humidityMonitor'
      - '--memory=256MB'
      - '--timeout=60s'
      - '--env-vars-file=.env.yaml'

timeout: '600s'